#!/usr/bin/env bash
# Dns A record lookup with dig command
# Checking the checker awk test

all_subs=( "www" "lb-01" "web-01" "web-02" )

execDig () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${all_subs[@]}"
    do
	execDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    execDig "$subdomain" "$domain"
fi
