#!/usr/bin/env bash
# Nginx server setup

sudo apt update -y && apt install nginx -y
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
