#!/usr/bin/env bash
# Nginx server setup

sudo apt update -y && sudo apt install nginx -y
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/location \/ {/a         add_header X-Served-By $HOSTNAME always;' /etc/nginx/sites-available/default
sudo service nginx start

