#!/usr/bin/env bash
# Debugging container
sudo ufw allow 'Nginx HTTP'
sudo rm -rf /etc/nginx/sites-enabled/*
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/                                  
sudo service nginx restart
