#!/usr/bin/env bash
# Bash script displays numbers from 1 to 100.
#   Displays FizzBuzz when the number is a multiple of 3 and 5
#   Displays Fizz when the number is multiple of 3
#   Displays Buzz when the number is a multiple of 5
#   Otherwise, displays the number in a list format

for var in {1..100}
do
    if (( var % 3 == 0 && var % 5 == 0 ))
    then
        echo FizzBuzz
    elif (( var % 3 == 0 ))
    then
        echo Fizz
    elif (( var % 5 == 0 ))
    then
        echo Buzz
    else
        echo $var
    fi
done
