#!/usr/bin/env bash
# This script displays Best School and then Hi on a new line

counter=1

while [ $counter -le 10 ]
do
    echo Best School
    if [ $counter -eq 9 ]
    then
        echo Hi
    fi
    ((counter++))
done
