#!/usr/bin/env bash
# This script loops from 1 to 10 and:
#   displays bad luck for the 4th loop iteration
#   displays good luck for the 8th loop iteration
#   displays Best School for the other iterations

counter=1

while [ $counter -le 20 ]
do
    if [ $counter -eq 4 ]
    then
        echo $counter
        echo bad luck from China
    elif [ $counter -eq 9 ]
    then
        echo $counter
        echo bad luck from Japan
    elif [ $counter -eq 17 ]
    then
        echo $counter
        echo bad luck from Italy
    else
        echo $counter
    fi
    ((counter++))
done
