#!/usr/bin/env bash
# This script loops from 1 to 10 and:
#   displays bad luck from China for the 4th loop iteration
#   displays bad luck from Japan for the 9th loop iteration
#   displays bad luck from Italy for the 17th loop  iterations

counter=1

while [ $counter -le 20 ]
do
    case $counter in
        4)
            echo $counter
            echo bad luck from China
            ;;
        9)
            echo $counter
            echo bad luck from Japan
            ;;
        17)
            echo $counter
            echo bad luck from Italy
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
