#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
#   display hours from 0 to 12
#   display minutes from 1 to 59

counter=0

while [ $counter -le 12 ]
do
    inner=1
    echo "Hour: $counter"
    ((counter++))

    while [ $inner -le 59 ]
    do
        echo $inner
        ((inner++))
    done
done
